# Generated by Django 5.1.6 on 2025-06-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E‑mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('idade', models.PositiveIntegerField(verbose_name='Idade')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível para contratação')),
                ('resumo', models.TextField(blank=True, verbose_name='Resumo profissional')),
                ('experiencia', models.TextField(blank=True, verbose_name='Experiência profissional')),
            ],
        ),
    ]
