# Generated by Django 5.2.4 on 2025-07-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postagem", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Postagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("autora", models.CharField(max_length=100, verbose_name="Autora")),
                ("conteudo", models.TextField(verbose_name="Conteúdo")),
                (
                    "resumo",
                    models.CharField(blank=True, max_length=255, verbose_name="Resumo"),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Categoria"
                    ),
                ),
                (
                    "data_publicacao",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Publicação"
                    ),
                ),
                (
                    "curtidas",
                    models.PositiveIntegerField(default=0, verbose_name="Curtidas"),
                ),
                (
                    "em_destaque",
                    models.BooleanField(default=False, verbose_name="Em destaque"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Candidato",
        ),
    ]
